name: Build Math Quiz APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências de sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libffi-dev libgl1-mesa-dev libgles2-mesa-dev ccache ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixin-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev openjdk-17-jdk

      - name: Aceitar licenças do Android SDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Instalar Buildozer e Cython
        run: |
          pip install --upgrade pip setuptools
          pip install buildozer cython

      - name: Gerar APK
        run: |
          buildozer -v android debug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: MathQuizAPK
          path: bin/*.apk

